{% set name = "sshtunnel" %}
  {% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f29ae41a1bd3afa64e9a31029bece2966e4be9a9641e8262372741e691c40d76

build:
  noarch: python
  entry_points:
    - sshtunnel = sshtunnel:_cli_main
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose"


requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - paramiko >=1.15.2

test:
  imports:
    - sshtunnel

about:
  home: http://github.com/pahaz/sshtunnel
  license: MIT
  license_file: LICENSE
  summary: 'Pure Python SSH tunnels'
  dev_url: https://github.com/pahaz/sshtunnel

extra:
  recipe-maintainers:
    - basnijholt
    - pahaz
    - fernandezcuesta
