{% set name = "sshtunnel" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sshtunnel-{{ version }}.tar.gz
  sha256: 3b0b36685b066704560991598a0c9587505635c76915d298771c5394abd98909

build:
  number: 1
  noarch: python
  entry_points:
    - sshtunnel=sshtunnel:_cli_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - paramiko >=1.15.2

test:
  imports:
    - sshtunnel
  commands:
    - pip check
    - sshtunnel --help
  requires:
    - pip

about:
  home: https://github.com/pahaz/sshtunnel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python SSH tunnels
  doc_url: https://github.com/pahaz/sshtunnel
  dev_url: https://github.com/pahaz/sshtunnel

extra:
  recipe-maintainers:
    - basnijholt
    - pahaz
    - fernandezcuesta
    - BrentDorsey
    - xylar
