{% set name = "sshtunnel" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f29ae41a1bd3afa64e9a31029bece2966e4be9a9641e8262372741e691c40d76

build:
  noarch: python
  entry_points:
    - sshtunnel = sshtunnel:_cli_main
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --verbose

requirements:
  host:
    - python >=2.7
    - pip >=18.1
    - setuptools >=34.0.0
    - paramiko >=1.15.2
  run:
    - paramiko

test:
  imports:
    - sshtunnel

about:
  home: http://github.com/pahaz/sshtunnel
  license: MIT
  license_family: MIT
  summary: 'Pure Python SSH tunnels'
  doc_url: https://github.com/pahaz/sshtunnel
  dev_url: https://github.com/pahaz/sshtunnel

extra:
  recipe-maintainers:
    - basnijholt
    - pahaz
    - fernandezcuesta
    - BrentDorsey
