{% set name = "sshtunnel" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f29ae41a1bd3afa64e9a31029bece2966e4be9a9641e8262372741e691c40d76

build:
  noarch: python
  entry_points:
    - sshtunnel = sshtunnel:_cli_main
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --verbose

requirements:
  host:
    - python >=2.7
    - pip >=18.1
    - setuptools >=34.0.0
    - paramiko >=1.15.2
  run:
    - paramiko

test:
  imports:
    - sshtunnel

about:
  home: http://github.com/pahaz/sshtunnel
  license: MIT
  license_family: MIT
  summary: 'Pure Python SSH tunnels'
  description: |
    sshtunnel Pure python SSH tunnels
    ====================
          Author - <a href="https://github.com/pahaz">Pahaz Blinov</a>
            Repo - <a href="https://github.com/pahaz/sshtunnel/">sshtunnel</a>
    Requirements - <a href="http://www.paramiko.org/">paramiko</a>

    Inspired by <a href="https://github.com/jmagnusson/bgtunnel">bgtunnel</a>, but it doesn't work on
    Windows.

    See: <a href="https://github.com/paramiko/paramiko/blob/master/demos/forward.py">demos/forward.py</a>
  dev_url: https://github.com/pahaz/sshtunnel

extra:
  recipe-maintainers:
    - basnijholt
    - pahaz
    - fernandezcuesta
    - BrentDorsey
