{% set name = "sshtunnel" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7cb0ea774db81bf91844db22de72a40aae8f7b0f9bb9ba0f666d474ef6bf9fc

build:
  noarch: python
  entry_points:
    - sshtunnel = sshtunnel:_cli_main
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --verbose

requirements:
  host:
    - python >=2.7
    - pip >=18.1
    - setuptools >=34.0.0
    - paramiko >=1.15.2
  run:
    - paramiko

test:
  imports:
    - sshtunnel

about:
  home: http://github.com/pahaz/sshtunnel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python SSH tunnels
  doc_url: https://github.com/pahaz/sshtunnel
  dev_url: https://github.com/pahaz/sshtunnel

extra:
  recipe-maintainers:
    - basnijholt
    - pahaz
    - fernandezcuesta
    - BrentDorsey
