{% set name = "sshtunnel" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0cac8a6a154c7a9651b42038e3f6cf35bb88c8ee4b94822b28a5b2fe7140f95

build:
  noarch: python
  entry_points:
    - sshtunnel = sshtunnel:_cli_main
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --verbose

requirements:
  host:
    - python >=2.7
    - pip >=18.1
    - setuptools >=34.0.0
    - paramiko >=1.15.2
  run:
    - paramiko

test:
  imports:
    - sshtunnel

about:
  home: http://github.com/pahaz/sshtunnel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python SSH tunnels
  doc_url: https://github.com/pahaz/sshtunnel
  dev_url: https://github.com/pahaz/sshtunnel

extra:
  recipe-maintainers:
    - basnijholt
    - pahaz
    - fernandezcuesta
    - BrentDorsey
